---
trigger:
  - none

resources:
  repositories:
    - repository: templates
      type: git
      name: ${project_name}/${repository_name_templates}

parameters:
  - name: terraform_cli_version
    displayName: Terraform CLI Version
    type: string
    default: 'latest'

lockBehavior: sequential

extends:
  template: ${ci_template_path}@templates
  parameters:
    root_module_folder_relative_path: ${root_module_folder_relative_path}
    terraform_cli_version: $${{ coalesce(parameters.terraform_cli_version, 'latest') }}
