---
trigger: none

variables:
  PARAMETERS_FILE_NAME: 'parameters.json'

stages:
  - stage: Validate
    displayName: 'Validate Bicep'
    jobs:
      - job: validate
        displayName: 'Bicep Build & Lint'
        pool:
          ${agent_pool_or_runner_configuration}
        steps:
          - checkout: self
            displayName: 'Checkout Bicep Module'

          - template: ./helpers/bicep-installer.yaml
            parameters:
              serviceConnection: '${service_connection_name_plan}'

          - task: PowerShell@2
            displayName: 'Bicep Build & Lint All Modules'
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                $output = @()
                Get-ChildItem -Recurse -Filter '*.bicep' -Exclude '*.bicep' | Where-Object { $_.FullName -notlike "*\.bicep\*" } | ForEach-Object {
                    Write-Information "==> Attempting Bicep Build For File: $_" -InformationAction Continue
                    $bicepOutput = bicep build $_.FullName 2>&1
                    if ($LastExitCode -ne 0)
                    {
                      foreach ($item in $bicepOutput) {
                        $output += "$($item) `r`n"
                      }
                    }
                    else
                    {
                      echo "Bicep Build Successful for File: $_"
                    }
                }
                if ($output.length -gt 0) {
                  throw $output
                }

  - stage: WhatIf
    displayName: 'What If'
    dependsOn: Validate
    jobs:
      - deployment: whatif
        displayName: 'What If Deployment'
        pool:
          ${agent_pool_or_runner_configuration}
        environment: '${environment_name_plan}'
        timeoutInMinutes: 0
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: 'Checkout Bicep Module'

                - template: ./helpers/bicep-variables.yaml
                  parameters:
                    parametersFileName: $(PARAMETERS_FILE_NAME)

                - template: ./helpers/bicep-installer.yaml
                  parameters:
                    serviceConnection: '${service_connection_name_plan}'

                - task: AzurePowerShell@5
                  displayName: 'Check for First Deployment'
                  inputs:
                    azureSubscription: '${service_connection_name_plan}'
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptType: "InlineScript"
                    Inline: |
                      $intRootMgId = "$(INTERMEDIATE_ROOT_MANAGEMENT_GROUP_ID)"

                      $managementGroups = Get-AzManagementGroup
                      $intRootMg = $managementGroups | Where-Object { $_.Name -eq $intRootMgId }

                      $firstDeployment = $true

                      if($intRootMg -eq $null) {
                        Write-Warning "Cannot find the $intRootMgId Management Group, so assuming this is the first deployment. We must skip what-if for some deployments since their dependent resources do not exist yet."
                      } else {
                        Write-Host "Found the $intRootMgId Management Group, so assuming this is not the first deployment."
                        $firstDeployment = $false
                      }

                      Write-Host "##vso[task.setvariable variable=FIRST_DEPLOYMENT;]$firstDeployment"

%{ for script_file in script_files ~}
                - template: ./helpers/bicep-deploy.yaml
                  parameters:
                    name: '${script_file.name}'
                    displayName: '${script_file.displayName}'
                    serviceConnection: '${service_connection_name_plan}'
                    templateFilePath: '${script_file.templateFilePath}'
                    templateParametersFilePath: '${script_file.templateParametersFilePath}'
                    managementGroupId: '${script_file.managementGroupIdVariable}'
                    subscriptionId: '${script_file.subscriptionIdVariable}'
                    resourceGroupName: '${script_file.resourceGroupNameVariable}'
                    location: '$(LOCATION)'
                    deploymentType: '${script_file.deploymentType}'
                    firstRunWhatIf: ${script_file.firstRunWhatIf}
                    whatIfEnabled: true

%{ endfor ~}
