---
stages:
  - stage: validate
    displayName: Validation Bicep
    variables:
      - group: ${variable_group_name}
      - name: parametersFileName
        value: parameters.json

    jobs:
      - job: validate
        displayName: Validate Bicep
        pool:
          ${agent_pool_configuration}
        steps:
          - checkout: self
            displayName: Checkout Repo

          - template: helpers/bicep-installer.yaml

          - pwsh: |
              if (Test-Path -Path ./custom-modules/*)
              {
                echo "##vso[task.setvariable variable=CUSTOM_MODULES;]true"
                echo "Set CUSTOM_MODULES to true"
              }
              else
              {
                echo "Set CUSTOM_MODULES to false"
              }
            workingDirectory: config
            displayName: Check for Custom Modules

          - pwsh: |
              $output = @()
              Get-ChildItem -Recurse -Filter '*.bicep' | ForEach-Object {
                  Write-Information "==> Attempting Bicep Build For File: $_" -InformationAction Continue
                  $bicepOutput = bicep build $_.FullName 2>&1
                  if ($LastExitCode -ne 0)
                  {
                    foreach ($item in $bicepOutput) {
                      $output += "$($item) `r`n"
                    }
                  }
                  else
                  {
                    echo "Bicep Build Successful for File: $_"
                  }
              }
              if ($output.length -gt 0) {
                throw $output
              }
            workingDirectory: config/custom-modules
            condition: eq(variables['CUSTOM_MODULES'], 'true')
            displayName: Bicep Build & Lint All Custom Modules
            
      - job: lint
        displayName: Lint Bicep
        pool:
          ${agent_pool_configuration}
        steps:
          - checkout: self
            displayName: Checkout Repo

          - task: DockerInstaller@0

          - bash: |
              docker version

              if [$? -eq 0 ]; then
                echo "Docker is installed and running"
              else
                echo "Docker is not running, you will need to use an alternative agent compute type that supports docker..."
                exit 0
              fi

              docker pull github/super-linter:latest
              docker run \
                -e RUN_LOCAL=true \
                -e VALIDATE_JSON=true \
                -e VALIDATE_MARKDOWN=true \
                -e VALIDATE_POWERSHELL=true \
                -e VALIDATE_YAML=true \
                -e VALIDATE_EDITORCONFIG=true \
                -e "FILTER_REGEX_EXCLUDE=.*upstream-releases/*|.*generateddocs/.*.bicep.md" \
                -v $(System.DefaultWorkingDirectory):/tmp/lint \
                github/super-linter
            displayName: Run github/super-linter

      - deployment: whatif
        displayName: What If Deploy with Bicep
        pool:
          ${agent_pool_configuration}
        environment: ${environment_name_plan}
        timeoutInMinutes: 0
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout Bicep Module

                - template: helpers/bicep-installer.yaml
                  parameters:
                    serviceConnection: '${service_connection_name_plan}'

                - template: helpers/bicep-variables.yaml
                  parameters:
                    parametersFileName: $(parametersFileName)

                - template: helpers/bicep-templates.yaml
                  parameters:
                    serviceConnection: '${service_connection_name_plan}'
                    whatIfEnabled: true
