---
name: Run Bicep AVM Deploy with Deployment Stack
description: Run Bicep AVM Deployment using Azure Deployment Stacks
inputs:
  displayName:
    description: 'Display Name'
    required: true
  templateFilePath:
    description: 'The path to the Bicep file'
    required: true
  templateParametersFilePath:
    description: 'The path to the parameters file'
    required: true
  managementGroupId:
    description: 'The root parent management group id'
    required: true
  subscriptionId:
    description: 'The subscription id'
    required: true
  resourceGroupName:
    description: 'The resource group name'
    required: true
  location:
    description: 'The location'
    required: true
  deploymentType:
    description: 'The deployment type (managementGroup, subscription, resourceGroup)'
    required: true
  firstRunWhatIf:
    description: 'Run a what-if on the first run'
    required: false
    default: 'false'
  networkType:
    description: 'The network type filter'
    required: false
    default: ''
  whatIfEnabled:
    description: 'Enable what-if mode (validation only, no deployment)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Run Bicep AVM Deploy with Deployment Stack
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $deploymentType = $env:DEPLOYMENT_TYPE
          $whatIfEnabled = $env:WHAT_IF_ENABLED -eq 'true'

          # Check if we should skip what-if for first deployment
          $firstDeploymentString = $env:firstDeployment
          $firstDeployment = $true
          if($firstDeploymentString -eq "") {
            $firstDeployment = $false
          } else {
            $firstDeployment = [System.Convert]::ToBoolean($firstDeploymentString)
          }

          $firstRunWhatIf = [System.Convert]::ToBoolean($env:FIRST_RUN_WHAT_IF)

          if($whatIfEnabled -and $firstDeployment -and !$firstRunWhatIf) {
            Write-Warning "Skipping the What-If check as the deployment is dependent on resources that do not exist yet..."
            exit 0
          }

          # Generate deployment name without timestamp for consistent deployment stack names
          $deploymentPrefix = "alz"
          $deploymentNameBase = $env:DISPLAY_NAME.Replace(" ", "-")

          $deploymentNameMaxLength = 64 - $deploymentPrefix.Length - 1

          if ($deploymentNameBase.Length -gt $deploymentNameMaxLength) {
            $deploymentNameBase = $deploymentNameBase.Substring(0, $deploymentNameMaxLength)
          }

          $deploymentName = "$deploymentPrefix-$deploymentNameBase"

          $modeText = if ($whatIfEnabled) { "What-If" } else { "Deployment Stack" }

          Write-Host "================================================" -ForegroundColor Blue
          Write-Host "Starting $modeText for $deploymentName" -ForegroundColor Blue
          Write-Host "================================================" -ForegroundColor Blue
          Write-Host ""
          Write-Host "Display Name: $env:DISPLAY_NAME" -ForegroundColor DarkGray
          Write-Host "Deployment Name: $deploymentName" -ForegroundColor DarkGray
          Write-Host "Template File Path: $env:TEMPLATE_FILE_PATH" -ForegroundColor DarkGray
          Write-Host "Template Parameters File Path: $env:TEMPLATE_PARAMETERS_FILE_PATH" -ForegroundColor DarkGray
          Write-Host "Management Group Id: $env:MANAGEMENT_GROUP_ID" -ForegroundColor DarkGray
          Write-Host "Subscription Id: $env:SUBSCRIPTION_ID" -ForegroundColor DarkGray
          Write-Host "Resource Group Name: $env:RESOURCE_GROUP_NAME" -ForegroundColor DarkGray
          Write-Host "Location: $env:LOCATION" -ForegroundColor DarkGray
          Write-Host "Deployment Type: $deploymentType" -ForegroundColor DarkGray
          Write-Host "What-If Mode: $whatIfEnabled" -ForegroundColor DarkGray
          Write-Host ""

          # Check if template files exist
          if (-not (Test-Path $env:TEMPLATE_FILE_PATH)) {
            Write-Error "Template file not found: $env:TEMPLATE_FILE_PATH"
            throw "Template file not found: $env:TEMPLATE_FILE_PATH"
          }
          Write-Host "✓ Template file exists: $env:TEMPLATE_FILE_PATH" -ForegroundColor Green

          if (-not (Test-Path $env:TEMPLATE_PARAMETERS_FILE_PATH)) {
            Write-Error "Template parameters file not found: $env:TEMPLATE_PARAMETERS_FILE_PATH"
            throw "Template parameters file not found: $env:TEMPLATE_PARAMETERS_FILE_PATH"
          }
          Write-Host "✓ Template parameters file exists: $env:TEMPLATE_PARAMETERS_FILE_PATH" -ForegroundColor Green
          Write-Host ""

          if ($whatIfEnabled) {
            # What-If mode - validation only using standard deployment with -WhatIf parameter
            Write-Host "Running in What-If mode (validation only)" -ForegroundColor Cyan
            Write-Host ""

            $whatIfParameters = @{
              DeploymentName        = $deploymentName
              TemplateFile          = $env:TEMPLATE_FILE_PATH
              TemplateParameterFile = $env:TEMPLATE_PARAMETERS_FILE_PATH
              WhatIf                = $true
              Verbose               = $true
            }

            try {
              switch ($deploymentType) {
                "managementGroup" {
                  $targetManagementGroupId = $env:MANAGEMENT_GROUP_ID
                  if ([string]::IsNullOrWhiteSpace($targetManagementGroupId)) {
                    $targetManagementGroupId = (Get-AzContext).Tenant.TenantId
                  }

                  Write-Host "Running Management Group What-If: $deploymentName" -ForegroundColor Cyan
                  $whatIfParameters.Location = $env:LOCATION
                  $whatIfParameters.ManagementGroupId = $targetManagementGroupId
                  $result = New-AzManagementGroupDeployment @whatIfParameters
                }
                "subscription" {
                  if (-not [string]::IsNullOrWhiteSpace($env:SUBSCRIPTION_ID)) {
                    Write-Host "Setting subscription context to: $env:SUBSCRIPTION_ID" -ForegroundColor Cyan
                    Select-AzSubscription -SubscriptionId $env:SUBSCRIPTION_ID | Out-Null
                  }

                  Write-Host "Running Subscription What-If: $deploymentName" -ForegroundColor Cyan
                  $whatIfParameters.Location = $env:LOCATION
                  $result = New-AzSubscriptionDeployment @whatIfParameters
                }
                "resourceGroup" {
                  if (-not [string]::IsNullOrWhiteSpace($env:SUBSCRIPTION_ID)) {
                    Write-Host "Setting subscription context to: $env:SUBSCRIPTION_ID" -ForegroundColor Cyan
                    Select-AzSubscription -SubscriptionId $env:SUBSCRIPTION_ID | Out-Null
                  }

                  Write-Host "Running Resource Group What-If: $deploymentName" -ForegroundColor Cyan
                  $whatIfParameters.ResourceGroupName = $env:RESOURCE_GROUP_NAME
                  $result = New-AzResourceGroupDeployment @whatIfParameters
                }
                default {
                  Write-Error "Invalid deployment type: $deploymentType"
                  throw "Invalid deployment type: $deploymentType"
                }
              }

              Write-Host ""
              Write-Host "================================================" -ForegroundColor Green
              Write-Host "✓ What-If Validation Succeeded: $deploymentName" -ForegroundColor Green
              Write-Host "================================================" -ForegroundColor Green
              Write-Host ""

            } catch {
              Write-Error "What-If validation failed: $($_.Exception.Message)"
              throw
            }

          } else {
            # Deployment Stack mode - actual deployment
            $stackParameters = @{
              Name                  = $deploymentName
              TemplateFile          = $env:TEMPLATE_FILE_PATH
              TemplateParameterFile = $env:TEMPLATE_PARAMETERS_FILE_PATH
              DenySettingsMode      = "None"
              ActionOnUnmanage      = "DeleteAll"
              Force                 = $true
              Verbose               = $true
            }

            $retryCount = 0
            $retryMax = 20
            $initialRetryDelay = 20
            $retryDelayIncrement = 10
            $finalSuccess = $false

            while ($retryCount -lt $retryMax) {
              if ($retryCount -gt 0) {
                $retryDelay = $initialRetryDelay + ($retryCount * $retryDelayIncrement)
                Write-Host "Retrying deployment stack after $retryDelay seconds..." -ForegroundColor Yellow
                Start-Sleep -Seconds $retryDelay
                Write-Host "Retry attempt $retryCount" -ForegroundColor Yellow
              }

              $result = $null

              try {
                switch ($deploymentType) {
                  "managementGroup" {
                    $targetManagementGroupId = $env:MANAGEMENT_GROUP_ID
                    if ([string]::IsNullOrWhiteSpace($targetManagementGroupId)) {
                      $targetManagementGroupId = (Get-AzContext).Tenant.TenantId
                    }

                    Write-Host "Creating Management Group Deployment Stack: $deploymentName" -ForegroundColor Cyan
                    $result = New-AzManagementGroupDeploymentStack @stackParameters -ManagementGroupId $targetManagementGroupId -Location $env:LOCATION
                  }
                  "subscription" {
                    if (-not [string]::IsNullOrWhiteSpace($env:SUBSCRIPTION_ID)) {
                      Write-Host "Setting subscription context to: $env:SUBSCRIPTION_ID" -ForegroundColor Cyan
                      Select-AzSubscription -SubscriptionId $env:SUBSCRIPTION_ID | Out-Null
                    }

                    Write-Host "Creating Subscription Deployment Stack: $deploymentName" -ForegroundColor Cyan
                    $result = New-AzSubscriptionDeploymentStack @stackParameters -Location $env:LOCATION
                  }
                  "resourceGroup" {
                    if (-not [string]::IsNullOrWhiteSpace($env:SUBSCRIPTION_ID)) {
                      Write-Host "Setting subscription context to: $env:SUBSCRIPTION_ID" -ForegroundColor Cyan
                      Select-AzSubscription -SubscriptionId $env:SUBSCRIPTION_ID | Out-Null
                    }

                    Write-Host "Creating Resource Group Deployment Stack: $deploymentName" -ForegroundColor Cyan
                    $result = New-AzResourceGroupDeploymentStack @stackParameters -ResourceGroupName $env:RESOURCE_GROUP_NAME
                  }
                  default {
                    Write-Error "Invalid deployment type: $deploymentType"
                    throw "Invalid deployment type: $deploymentType"
                  }
                }

                if ($result.ProvisioningState -eq "Succeeded") {
                  $finalSuccess = $true
                  Write-Host ""
                  Write-Host "================================================" -ForegroundColor Green
                  Write-Host "✓ Deployment Stack Succeeded: $deploymentName" -ForegroundColor Green
                  Write-Host "================================================" -ForegroundColor Green
                  Write-Host ""
                  break
                } else {
                  Write-Warning "Deployment stack finished with state: $($result.ProvisioningState)"
                  $retryCount++
                }
              } catch {
                Write-Warning "Deployment stack failed with error: $($_.Exception.Message)"
                $retryCount++

                if ($retryCount -ge $retryMax) {
                  Write-Error "Deployment stack failed after $retryMax attempts"
                  throw
                }
              }
            }

            if (-not $finalSuccess) {
              Write-Error "Deployment stack did not succeed after $retryMax attempts"
              throw "Deployment stack did not succeed after $retryMax attempts"
            }
          }
      env:
        DISPLAY_NAME: $${{ inputs.displayName }}
        TEMPLATE_FILE_PATH: $${{ inputs.templateFilePath }}
        TEMPLATE_PARAMETERS_FILE_PATH: $${{ inputs.templateParametersFilePath }}
        MANAGEMENT_GROUP_ID: $${{ inputs.managementGroupId }}
        SUBSCRIPTION_ID: $${{ inputs.subscriptionId }}
        RESOURCE_GROUP_NAME: $${{ inputs.resourceGroupName }}
        LOCATION: $${{ inputs.location }}
        DEPLOYMENT_TYPE: $${{ inputs.deploymentType }}
        FIRST_RUN_WHAT_IF: $${{ inputs.firstRunWhatIf }}
        WHAT_IF_ENABLED: $${{ inputs.whatIfEnabled }}
