---
trigger:
  branches:
    include:
      - main

parameters:
  - name: skipWhatIf
    displayName: Skip What If Check?
    type: boolean
    default: false

resources:
  repositories:
    - repository: templates
      type: git
      name: ${project_name}/${repository_name_templates}

lockBehavior: sequential

extends:
  template: ${cd_template_path}@templates
  parameters:
    skipWhatIf: $${{ parameters.skipWhatIf }}
