---
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: ${project_name}/${repository_name_templates}

lockBehavior: sequential

extends:
  template: ${cd_template_path}@templates
