---
trigger: none

parameters:
  - name: skip_what_if
    displayName: 'Skip What-If Stage'
    type: boolean
    default: false
%{ for script_file in script_files ~}
  - name: ${script_file.name}
    displayName: '${script_file.displayName}'
    type: boolean
    default: true
%{ endfor ~}

variables:
  PARAMETERS_FILE_NAME: 'parameters.json'

stages:
  - stage: WhatIf
    displayName: 'What If'
    condition: ne('$${{ parameters.skip_what_if }}', true)
    jobs:
      - deployment: whatif
        displayName: 'What If Deployment'
        pool:
          ${agent_pool_configuration}
        environment: '${environment_name_plan}'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: PowerShell@2
                  displayName: 'Show Parameters'
                  inputs:
                    targetType: 'inline'
                    pwsh: true
                    script: |
                      Write-Host "Parameters:"
                      Write-Host "skip_what_if: $${{ parameters.skip_what_if }}"
%{ for script_file in script_files ~}
                      Write-Host "${script_file.name}: $${{ parameters['${script_file.name}'] }}"
%{ endfor ~}

                - checkout: self
                  displayName: 'Checkout Bicep Module'

                - template: ./helpers/bicep-avm-variables.yaml
                  parameters:
                    parametersFileName: $(PARAMETERS_FILE_NAME)

                - task: AzurePowerShell@5
                  displayName: 'Check for First Deployment'
                  inputs:
                    azureSubscription: '${service_connection_name_plan}'
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptType: "InlineScript"
                    Inline: |
                      $managementGroupId = $env:MANAGEMENT_GROUP_ID
                      $intRootMgId = "$managementGroupId-int-root"
                      $managementGroups = Get-AzManagementGroup
                      $intRootMg = $managementGroups | Where-Object { $_.Name -eq $intRootMgId }

                      $firstDeployment = $true

                      if($intRootMg -eq $null) {
                        Write-Warning "Cannot find the $intRootMgId Management Group, so assuming this is the first deployment. We must skip what-if for some deployments since their dependent resources do not exist yet."
                      } else {
                        Write-Host "Found the $intRootMgId Management Group, so assuming this is not the first deployment."
                        $firstDeployment = $false
                      }

                      Write-Host "##vso[task.setvariable variable=FIRST_DEPLOYMENT;]$firstDeployment"

                - template: ./helpers/bicep-avm-installer.yaml
                  parameters:
                    serviceConnection: '${service_connection_name_plan}'

%{ for script_file in script_files ~}
%{ if try(script_file.networkType, "") != "" ~}
                - $${{ if and(eq(parameters['${script_file.name}'], true), eq(variables['NETWORK_TYPE'], '${script_file.networkType}')) }}:
                  - template: ./helpers/bicep-avm-deploy.yaml
                    parameters:
                      displayName: '${script_file.displayName} (Network Type: ${script_file.networkType})'
                      serviceConnection: '${service_connection_name_plan}'
                      templateFilePath: '${script_file.templateFilePath}'
                      templateParametersFilePath: '${script_file.templateParametersFilePath}'
                      managementGroupId: '${script_file.managementGroupIdVariable}'
                      subscriptionId: '${script_file.subscriptionIdVariable}'
                      resourceGroupName: '${script_file.resourceGroupNameVariable}'
                      location: '$(LOCATION)'
                      deploymentType: '${script_file.deploymentType}'
                      firstRunWhatIf: ${script_file.firstRunWhatIf}
                      networkType: '${script_file.networkType}'
                      whatIfEnabled: true

%{ else ~}
                - $${{ if eq(parameters['${script_file.name}'], true) }}:
                  - template: ./helpers/bicep-avm-deploy.yaml
                    parameters:
                      displayName: '${script_file.displayName}'
                      serviceConnection: '${service_connection_name_plan}'
                      templateFilePath: '${script_file.templateFilePath}'
                      templateParametersFilePath: '${script_file.templateParametersFilePath}'
                      managementGroupId: '${script_file.managementGroupIdVariable}'
                      subscriptionId: '${script_file.subscriptionIdVariable}'
                      resourceGroupName: '${script_file.resourceGroupNameVariable}'
                      location: '$(LOCATION)'
                      deploymentType: '${script_file.deploymentType}'
                      firstRunWhatIf: ${script_file.firstRunWhatIf}
                      whatIfEnabled: true

%{ endif ~}
%{ endfor ~}

  - stage: Deploy
    displayName: 'Deploy'
    dependsOn: WhatIf
    condition: and(not(failed()), not(canceled()))
    jobs:
      - deployment: deploy
        displayName: 'Deploy Bicep'
        pool:
          ${agent_pool_configuration}
        environment: '${environment_name_apply}'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: PowerShell@2
                  displayName: 'Show Parameters'
                  inputs:
                    targetType: 'inline'
                    pwsh: true
                    script: |
                      Write-Host "Parameters:"
                      Write-Host "skip_what_if: $${{ parameters.skip_what_if }}"
%{ for script_file in script_files ~}
                      Write-Host "${script_file.name}: $${{ parameters['${script_file.name}'] }}"
%{ endfor ~}

                - checkout: self
                  displayName: 'Checkout Bicep Module'

                - template: ./helpers/bicep-avm-variables.yaml
                  parameters:
                    parametersFileName: $(PARAMETERS_FILE_NAME)

                - task: AzurePowerShell@5
                  displayName: 'Check for First Deployment'
                  inputs:
                    azureSubscription: '${service_connection_name_apply}'
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptType: "InlineScript"
                    Inline: |
                      $managementGroupId = $env:MANAGEMENT_GROUP_ID
                      $intRootMgId = "$managementGroupId-int-root"
                      $managementGroups = Get-AzManagementGroup
                      $intRootMg = $managementGroups | Where-Object { $_.Name -eq $intRootMgId }

                      $firstDeployment = $true

                      if($intRootMg -eq $null) {
                        Write-Warning "Cannot find the $intRootMgId Management Group, so assuming this is the first deployment."
                      } else {
                        Write-Host "Found the $intRootMgId Management Group, so assuming this is not the first deployment."
                        $firstDeployment = $false
                      }

                      Write-Host "##vso[task.setvariable variable=FIRST_DEPLOYMENT;]$firstDeployment"

                - template: ./helpers/bicep-avm-installer.yaml
                  parameters:
                    serviceConnection: '${service_connection_name_apply}'

%{ for script_file in script_files ~}
%{ if try(script_file.networkType, "") != "" ~}
                - $${{ if and(eq(parameters['${script_file.name}'], true), eq(variables['NETWORK_TYPE'], '${script_file.networkType}')) }}:
                  - template: ./helpers/bicep-avm-deploy.yaml
                    parameters:
                      displayName: '${script_file.displayName} (Network Type: ${script_file.networkType})'
                      serviceConnection: '${service_connection_name_apply}'
                      templateFilePath: '${script_file.templateFilePath}'
                      templateParametersFilePath: '${script_file.templateParametersFilePath}'
                      managementGroupId: '${script_file.managementGroupIdVariable}'
                      subscriptionId: '${script_file.subscriptionIdVariable}'
                      resourceGroupName: '${script_file.resourceGroupNameVariable}'
                      location: '$(LOCATION)'
                      deploymentType: '${script_file.deploymentType}'
                      firstRunWhatIf: ${script_file.firstRunWhatIf}
                      networkType: '${script_file.networkType}'
                      whatIfEnabled: false

%{ else ~}
                - $${{ if eq(parameters['${script_file.name}'], true) }}:
                  - template: ./helpers/bicep-avm-deploy.yaml
                    parameters:
                      displayName: '${script_file.displayName}'
                      serviceConnection: '${service_connection_name_apply}'
                      templateFilePath: '${script_file.templateFilePath}'
                      templateParametersFilePath: '${script_file.templateParametersFilePath}'
                      managementGroupId: '${script_file.managementGroupIdVariable}'
                      subscriptionId: '${script_file.subscriptionIdVariable}'
                      resourceGroupName: '${script_file.resourceGroupNameVariable}'
                      location: '$(LOCATION)'
                      deploymentType: '${script_file.deploymentType}'
                      firstRunWhatIf: ${script_file.firstRunWhatIf}
                      whatIfEnabled: false

%{ endif ~}
%{ endfor ~}
