---
trigger:
  branches:
    include:
      - main

parameters:
  - name: skipWhatIf
    displayName: Skip What If Check?
    type: boolean
    default: false
%{ for script_file in script_files ~}
  - name: ${script_file.name}
    displayName: 'Run Step: ${script_file.displayName}'
    type: boolean
    default: true
%{ endfor ~}
  - name: destroy
    displayName: "[DANGER!] Destroy? [DANGER!]"
    type: boolean
    default: false

resources:
  repositories:
    - repository: templates
      type: git
      name: ${project_name}/${repository_name_templates}

lockBehavior: sequential

extends:
  template: ${cd_template_path}@templates
  parameters:
    skipWhatIf: $${{ parameters.skipWhatIf }}
    destroy: $${{ parameters.destroy }}
%{ for script_file in script_files ~}
    ${script_file.name}: $${{ parameters.${script_file.name} }}
%{ endfor ~}
