---
name: Continuous Delivery
on:
  workflow_call:
    inputs:
      skip_what_if:
        default: false
        type: boolean
%{ for script_file in script_files ~}
      ${script_file.name}:
        type: boolean
        default: true
%{ endfor ~}

jobs:
  whatif:
    name: What If
    runs-on:
      ${agent_pool_or_runner_configuration}
    concurrency: ${concurrency_value}
    environment: ${environment_name_plan}
    permissions:
      id-token: write
      contents: read
    if: $${{ !inputs.skip_what_if }}
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Show inputs
        run: |
          Write-Host '$${{ toJson(inputs) }}'
        shell: pwsh

      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Get Bicep Variables
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-variables@main
        with:
          parameters_file_name: $${{ env.PARAMETERS_FILE_NAME }}

      - name: Install Bicep and Update Az Module
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-installer@main

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: $${{ vars.AZURE_CLIENT_ID }}
          tenant-id: $${{ vars.AZURE_TENANT_ID }}
          subscription-id: $${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Check for First Deployment
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-first-deployment-check@main
        with:
          managementGroupId: $${{ env.MANAGEMENT_GROUP_ID }}

%{ for script_file in script_files ~}
      - name: 'Plan: ${script_file.displayName}'
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-deploy@main
        if: $${{ inputs.${script_file.name} }}
        with:
          name: '${script_file.name}'
          displayName: '${script_file.displayName}'
          templateFilePath: '${script_file.templateFilePath}'
          templateParametersFilePath: '${script_file.templateParametersFilePath}'
          managementGroupId: '${script_file.managementGroupIdVariable}'
          subscriptionId: '${script_file.subscriptionIdVariable}'
          resourceGroupName: '${script_file.resourceGroupNameVariable}'
          location: '$${{ env.LOCATION }}'
          deploymentType: '${script_file.deploymentType}'
          firstRunWhatIf: '${script_file.firstRunWhatIf}'
          whatIfEnabled: 'true'

%{ endfor ~}

  deploy:
    name: Deploy
    needs: whatif
    if: $${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    runs-on:
      ${agent_pool_or_runner_configuration}
    concurrency: ${concurrency_value}
    environment: ${environment_name_apply}
    permissions:
      id-token: write
      contents: read
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Show inputs
        run: |
          Write-Host '$${{ toJson(inputs) }}'
        shell: pwsh

      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Get Bicep Variables
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-variables@main
        with:
          parameters_file_name: $${{ env.PARAMETERS_FILE_NAME }}

      - name: Install Bicep and Update Az Module
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-installer@main

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: $${{ vars.AZURE_CLIENT_ID }}
          tenant-id: $${{ vars.AZURE_TENANT_ID }}
          subscription-id: $${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

%{ for script_file in script_files ~}
      - name: 'Deploy: ${script_file.displayName}'
        uses: ${project_or_organization_name}/${repository_name_templates}/.github/actions/bicep-deploy@main
        if: $${{ inputs.${script_file.name} }}
        with:
          name: '${script_file.name}'
          displayName: '${script_file.displayName}'
          templateFilePath: '${script_file.templateFilePath}'
          templateParametersFilePath: '${script_file.templateParametersFilePath}'
          managementGroupId: '${script_file.managementGroupIdVariable}'
          subscriptionId: '${script_file.subscriptionIdVariable}'
          resourceGroupName: '${script_file.resourceGroupNameVariable}'
          location: '$${{ env.LOCATION }}'
          deploymentType: '${script_file.deploymentType}'

%{ endfor ~}
