---
name: Continuous Delivery
on:
  workflow_call:
    inputs:
      skip_what_if:
        required: true
        default: false
        type: boolean
%{ for script_file in script_files ~}
      ${script_file.name}:
        required: true
        type: boolean
        default: true
%{ endfor ~}
      destroy:
        required: true
        default: false
        type: boolean

jobs:
  whatif:
    name: What If
    runs-on:
      ${runner_name}
    concurrency: ${backend_azure_storage_account_container_name}
    environment: ${environment_name_plan}
    permissions:
      id-token: write
      contents: read
    if: $${{ github.event.inputs.skip_what_if == false)
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: 
        uses: ${organization_name}/${repository_name_templates}/.github/workflows/helpers/bicep-variables.yaml@main
        with:
          parameters_file_name: $${{ env.PARAMETERS_FILE_NAME }}
