---
name: 02 Azure Landing Zones Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_what_if:
        description: 'Skip What If Check?'
        type: boolean
        default: false
%{ for script_file_group in script_file_groups ~}
      ${script_file_group.name}:
        description: 'Run Steps: ${script_file_group.displayName}'
        type: boolean
        default: true
%{ endfor ~}

jobs:
  plan_and_apply:
    uses: ${project_or_organization_name}/${repository_name_templates}/${cd_template_path}@main
    name: 'CD'
    permissions:
      id-token: write
      contents: read
    with:
      skip_what_if: $${{ github.event_name != 'workflow_dispatch' && false || inputs.skip_what_if == true }}
%{ for script_file in script_files ~}
      ${script_file.name}: $${{ github.event_name != 'workflow_dispatch' && true || inputs.${script_file.group} == true }}
%{ endfor ~}
