---
name: fmt test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

concurrency:
  group: docsfmttest-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docsfmttest:
    name: fmt test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.20.x'
          cache-dependency-path: tests/go.sum

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Check fmt and docs
        run: |
          echo "==> Running make fmt & make docs"
          make fmt
          echo "==> Testing for changes to tracked files"
          CHANGES=$(git status -suno)
          if [ "$CHANGES" ]; then
            echo "Repository formatting or documentation is not correct."
            echo "Run 'make fmt && make docs' locally and commit the changes to fix."
            exit 1
          fi
