---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Zip and Tar
        run: |
          mkdir bootstrap
          cp -r .config bootstrap
          cp -r alz bootstrap
          cp -r modules bootstrap
          cd bootstrap
          tar -cvzf ../bootstrap_modules.tar.gz .
          zip -r ../bootstrap_modules.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bootstrap_modules
          path: |
            bootstrap_modules.tar.gz
            bootstrap_modules.zip

      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./bootstrap_modules.tar.gz
            ./bootstrap_modules.zip
